# Generated by Django 3.1.5 on 2021-04-21 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrestlink',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
