# Generated by Django 3.1.5 on 2021-01-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComposerRelationship',
            new_name='FollowComposer',
        ),
    ]
