# Generated by Django 3.1.5 on 2021-01-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0003_remove_composerprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composerprofile',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
