# Generated by Django 3.1.5 on 2021-02-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0004_auto_20210127_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='composerprofile',
            name='can_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='composerprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='composerprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
