# Generated by Django 3.1.5 on 2021-02-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0005_auto_20210212_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='composerprofile',
            name='current_sales_percentage',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
