# Generated by Django 3.1.5 on 2021-02-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0006_composerprofile_current_sales_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='composerprofile',
            name='all_time_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='composerprofile',
            name='current_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
