# Generated by Django 3.1.5 on 2021-03-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0008_userpaymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymenthistory',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
