# Generated by Django 3.1.5 on 2021-03-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0010_auto_20210319_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymenthistory',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
