# Generated by Django 3.1.5 on 2021-03-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0011_userpaymenthistory_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymenthistory',
            name='cart_id',
            field=models.TextField(default=''),
        ),
    ]
