# Generated by Django 3.1.5 on 2021-03-19 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0012_userpaymenthistory_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymenthistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userpaymenthistory',
            name='payment_type',
            field=models.CharField(default='pay in', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpaymenthistory',
            name='cart_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
