# Generated by Django 3.1.5 on 2021-03-25 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0015_userpaymentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentlog',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 25)),
        ),
    ]
