# Generated by Django 3.1.5 on 2021-03-26 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0016_auto_20210325_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentlog',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 26)),
        ),
        migrations.AlterField(
            model_name='userpaymentlog',
            name='log_type',
            field=models.CharField(default='sales', max_length=10),
        ),
    ]
