# Generated by Django 3.1.5 on 2021-03-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0017_auto_20210326_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentlog',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
