# Generated by Django 3.1.5 on 2021-03-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0018_userpaymentlog_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='composerprofile',
            name='download',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
