# Generated by Django 3.1.5 on 2021-04-12 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0019_composerprofile_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composerprofile',
            name='current_sales_percentage',
        ),
        migrations.AlterField(
            model_name='userpaymentlog',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 12)),
        ),
    ]
