# Generated by Django 3.1.5 on 2021-04-23 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0022_auto_20210421_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentlog',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 23)),
        ),
    ]
