# Generated by Django 3.1.5 on 2021-04-26 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0025_auto_20210425_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentlog',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 26)),
        ),
    ]
