# Generated by Django 3.1.5 on 2021-04-28 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0026_auto_20210426_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composerprofile',
            name='download',
        ),
        migrations.AlterField(
            model_name='userpaymentlog',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 28)),
        ),
    ]
