# Generated by Django 3.1.5 on 2021-05-08 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0029_composerprofile_country_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='composeraccount',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='composeraccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='composeraccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='composeraccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userpaymentlog',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 8)),
        ),
    ]
