# Generated by Django 3.1.5 on 2021-05-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0034_auto_20210514_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymenthistory',
            name='bank_name_paid_to',
        ),
        migrations.RemoveField(
            model_name='userpaymenthistory',
            name='bank_paid_to',
        ),
        migrations.RemoveField(
            model_name='userpaymenthistory',
            name='email_paid_to',
        ),
    ]
