# Generated by Django 3.1.5 on 2021-06-07 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0036_auto_20210514_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymenthistory',
            name='payout_completed',
        ),
        migrations.AddField(
            model_name='composerprofile',
            name='can_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpaymentlog',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 7)),
        ),
    ]
