# Generated by Django 3.1.5 on 2021-06-09 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0041_sheetmusic_point'),
        ('composer', '0037_auto_20210607_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymenthistory',
            name='cart_item',
            field=models.ManyToManyField(null=True, to='musicStore.Score_sale'),
        ),
        migrations.AlterField(
            model_name='userpaymentlog',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 9)),
        ),
    ]
