# Generated by Django 3.1.5 on 2021-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0039_remove_userpaymenthistory_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymenthistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
