# Generated by Django 3.1.5 on 2022-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0042_score_rejected'),
        ('composer', '0040_auto_20210609_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymenthistory',
            name='cart_item',
            field=models.ManyToManyField(to='musicStore.Score_sale'),
        ),
        migrations.AlterField(
            model_name='userpaymentlog',
            name='date',
            field=models.DateField(),
        ),
    ]
