# Generated by Django 3.1.5 on 2021-01-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0002_auto_20210119_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_instrument',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='skill_level',
            field=models.CharField(default='Beginner', max_length=10),
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='video_link',
            field=models.TextField(default='Link'),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
