# Generated by Django 3.1.5 on 2021-02-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0003_auto_20210122_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetmusic',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='sheetmusic',
            name='link_to_original_pdf',
        ),
        migrations.RemoveField(
            model_name='sheetmusic',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sheetmusic',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='sheetmusic',
            name='genre',
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='genre',
            field=models.ManyToManyField(to='musicStore.Genre'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('sheet', models.FileField(blank=True, null=True, upload_to='')),
                ('link_to_original_pdf', models.TextField()),
                ('main_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicStore.sheetmusic')),
            ],
        ),
    ]
