# Generated by Django 3.1.5 on 2021-02-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0004_auto_20210208_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusic',
            name='myfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
