# Generated by Django 3.1.5 on 2021-02-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0006_auto_20210210_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet_order',
            name='sheet',
        ),
        migrations.AddField(
            model_name='sheet_order',
            name='score',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musicStore.score'),
        ),
    ]
