# Generated by Django 3.1.5 on 2021-02-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0007_auto_20210210_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet_order',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicStore.score'),
        ),
    ]
