# Generated by Django 3.1.5 on 2021-02-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0008_auto_20210210_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetmusic',
            old_name='reting',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='sheetmusic',
            name='myfile',
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
