# Generated by Django 3.1.5 on 2021-02-12 16:03

from django.db import migrations, models
import sheet_music_africa.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0010_auto_20210212_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='link_to_original_pdf',
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='score',
            name='sheet',
            field=models.FileField(blank=True, null=True, storage=sheet_music_africa.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
