# Generated by Django 3.1.5 on 2021-02-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0011_auto_20210212_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='audio',
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
