# Generated by Django 3.1.5 on 2021-02-12 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicStore', '0012_auto_20210212_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added_to_cart', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloadable', models.BooleanField(default=False)),
                ('date_purchased', models.DateTimeField()),
                ('purchased_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_percentage', models.PositiveIntegerField(default=80)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicStore.score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Sheet_order',
        ),
    ]
