# Generated by Django 3.1.5 on 2021-02-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0014_auto_20210212_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_sale',
            name='date_purchased',
            field=models.DateTimeField(blank=True),
        ),
    ]
