# Generated by Django 3.1.5 on 2021-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0015_auto_20210213_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_sale',
            name='purchased_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
