# Generated by Django 3.1.5 on 2021-03-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0020_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusic',
            name='discription',
            field=models.TextField(default=''),
        ),
    ]
