# Generated by Django 3.1.5 on 2021-03-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0024_sheetmusic_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score_sale',
            name='seller_percentage',
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='percentage',
            field=models.PositiveIntegerField(default=65),
        ),
    ]
