# Generated by Django 3.1.5 on 2021-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0025_auto_20210316_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
