# Generated by Django 3.1.5 on 2021-03-24 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicStore', '0026_auto_20210317_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SheetReview',
            new_name='My_review',
        ),
    ]
