# Generated by Django 3.1.5 on 2021-04-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0028_auto_20210325_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusic',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
