# Generated by Django 3.1.5 on 2021-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0029_sheetmusic_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='video_link',
            field=models.TextField(default=''),
        ),
    ]
