# Generated by Django 3.1.5 on 2021-04-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0030_auto_20210423_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='skill_level',
            field=models.CharField(default='Beginner', max_length=15),
        ),
    ]
