# Generated by Django 3.1.5 on 2021-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0031_auto_20210423_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
