# Generated by Django 3.1.5 on 2021-04-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0033_sheetmusic_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetmusic',
            options={'ordering': ['-verified']},
        ),
    ]
