# Generated by Django 3.1.5 on 2021-04-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0034_auto_20210426_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetmusic',
            options={'ordering': ['verified']},
        ),
    ]
