# Generated by Django 3.1.5 on 2021-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0035_auto_20210428_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_sale',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
    ]
