# Generated by Django 3.1.5 on 2021-04-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0036_auto_20210430_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='score_sale',
            name='purchased_percentage',
            field=models.PositiveIntegerField(default=65),
        ),
    ]
