# Generated by Django 3.1.5 on 2021-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0037_score_sale_purchased_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='score_sale',
            name='seller_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
