# Generated by Django 3.1.5 on 2021-06-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0039_sheetmusic_rejected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetmusic',
            options={'ordering': ['-rejected', 'verified']},
        ),
    ]
