# Generated by Django 3.1.5 on 2021-06-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0040_auto_20210607_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusic',
            name='point',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
