# Generated by Django 3.1.5 on 2022-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0042_score_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusic',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
