# Generated by Django 3.1.5 on 2022-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0044_auto_20220722_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='composed_by',
            field=models.TextField(blank=True, default=''),
        ),
    ]
