# Generated by Django 3.1.5 on 2021-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='negative_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='positive_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
