# Generated by Django 3.1.5 on 2021-04-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0002_auto_20210420_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preference',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
