# Generated by Django 3.1.5 on 2022-09-24 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameprofile_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameprofile',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.competition'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
