# Generated by Django 3.1.5 on 2022-09-24 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20220924_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.competition'),
        ),
    ]
