# Generated by Django 3.1.5 on 2022-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20220924_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('PEN', 'PENDING'), ('STA', 'STARTED'), ('END', 'ENDED')], default='PEN', max_length=3),
        ),
    ]
