# Generated by Django 3.1.5 on 2022-09-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20220927_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='can_compete',
        ),
        migrations.RemoveField(
            model_name='gameprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='gameprofile',
            name='token',
        ),
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(default='Virtual', max_length=200),
        ),
        migrations.RemoveField(
            model_name='gameprofile',
            name='competition',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='competition',
            field=models.ManyToManyField(to='game.Competition'),
        ),
    ]
