# Generated by Django 3.1.5 on 2022-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20220927_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='competition',
            field=models.ManyToManyField(blank=True, null=True, to='game.Competition'),
        ),
    ]
