# Generated by Django 3.1.5 on 2022-09-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20220927_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='competition',
            field=models.ManyToManyField(blank=True, to='game.Competition'),
        ),
    ]
