# Generated by Django 3.1.5 on 2022-09-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20220927_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='nickname',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
