# Generated by Django 3.1.5 on 2022-10-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20220928_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='state',
            field=models.CharField(default='Edo', max_length=30),
        ),
    ]
