# Generated by Django 3.1.5 on 2022-10-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20221025_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
