# Generated by Django 3.1.5 on 2022-10-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20221025_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
