# Generated by Django 3.1.5 on 2022-11-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_scorelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='span',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
