# Generated by Django 3.1.5 on 2022-11-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_competition_span'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='time_started',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
