# Generated by Django 3.1.5 on 2022-11-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_competition_time_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='time_started',
        ),
        migrations.AlterField(
            model_name='competition',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
