# Generated by Django 3.1.5 on 2022-11-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20221102_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='high_score',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
