# Generated by Django 3.1.5 on 2022-11-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_gameprofile_high_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameprofile',
            options={'ordering': ['-high_score']},
        ),
        migrations.DeleteModel(
            name='ScoreLog',
        ),
    ]
