# Generated by Django 3.1.5 on 2021-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('month', models.PositiveIntegerField(blank=True)),
                ('year', models.PositiveIntegerField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('composers_paid_to', models.TextField()),
            ],
        ),
    ]
