# Generated by Django 3.1.5 on 2021-05-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchpayout',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
