# Generated by Django 3.1.5 on 2021-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0003_auto_20210509_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchpayout',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batchpayout',
            name='composers_paid_to',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batchpayout',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
