# Generated by Django 3.1.5 on 2021-05-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0032_auto_20210509_1449'),
        ('payout', '0004_auto_20210509_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchpayout',
            name='composers_paid_to',
        ),
        migrations.AddField(
            model_name='batchpayout',
            name='composers_paid_to',
            field=models.ManyToManyField(null=True, to='composer.ComposerProfile'),
        ),
    ]
