# Generated by Django 3.1.5 on 2021-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0032_auto_20210509_1449'),
        ('payout', '0005_auto_20210509_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpayout',
            name='composers_paid_to',
            field=models.ManyToManyField(blank=True, null=True, to='composer.ComposerProfile'),
        ),
    ]
