# Generated by Django 3.1.5 on 2021-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0006_auto_20210509_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpayout',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchpayout',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
