# Generated by Django 3.1.5 on 2021-05-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0007_auto_20210509_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpayout',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
